#+TITLE: 数据库三大范式
   [[https://juejin.cn/post/6844904190427430920][参考博客]]
   + 第一范式 :: 第一范式(1NF)要求数据库表的每一列都是不可分割的原子数据项。
   + 第二范式 :: 在1NF的基础上，非属性码的属性必须完全依赖于主码。（在1NF基础上消除非属性码的属性对主码的部分函数依赖）
     + 依赖函数（完全、部分、传递）
       依赖函数: A -> B,如果通过A属性(或属性组)的值可以确定唯一的B属性的值，则可以称为B依赖于A（->符号是确定关系)。例如：可以通过学号来确定姓名，可以通过学号和课程来确定该课程的分数等等。
	 - 完全函数依赖 :: A - > B，如果A是一个属性组，则B属性的确定需要依赖A属性组中的所有属性值。例如：分数的确定需要依赖于学号和课程，而学号和课程可以称为一个属性组。如果有学号没有课程，我们只知道是谁的分数，而不知道是那一学科的分数。如果有课程没有学号，那我们只知道是哪一个学科的分数，而不知道是谁的分数。所以该属性组的两个值是必不可少的。这就是完全函数依赖。
	 - 部分函数依赖 :: A - > B，如果A是一个属性组，则B属性的确定需要依赖A属性组中的部分属性值。例如：如果一个属性组中有两个属性值，它们分别是学号和课程名称。那姓名的确定只依赖这个属性组中的学号，于课程名称无关。简单来说，依赖于属性组的中部分成员即可成为部分函数依赖。
	 - 传递函数依赖 ::  A - > B - > C，传递函数依赖就是一个依赖的传递关系。通过确定A来确定B，确定了B之后，也就可以确定C，三者的依赖关系就是C依赖于B，B依赖于A。例如：我们可以通过学号来确定这位学生所在的系部，再通过系部来确定系主任是谁。而这个三者的依赖关系就是一种传递函数依赖。
     + 候选码、主属性码与非属性码
       - 码 :: 如果在一张表中，一个属性或属性组，被其他所有属性所完全函数依赖 ，则称这个属性（或属性组）为该表的候选码，简称码。然而码又分为主属性码和非属性码。例如：分数的确定没有学号和课程是不行的，所以分数完全函数依赖于课程和学号。
       - 主属性码 :: 主属性码也叫主码，即在所有候选码挑选一个做主码，这里相当于是主键。例如：分数完全函数依赖于课程和学号。该码属性组中的值就有课程、学号和分数，所以我们要在三个候选码中，挑选一个做主码，那就可以挑选学号。
       - 非属性码 :: 除主码属性组以外的属性，叫做非属性码。例如：在分数完全函数依赖于课程和学号时，其中学号已经让我们选为主码。那么我们就可以确定，除了学号以外的属性值，其他的属性值都是非属性码。也就是说在这个完全函数依赖关系中，课程和分数是非属性码。
     

   + 第三范式 :: 在2NF的基础上，消除传递依赖。