#+TITLE: Ajax 笔记

 *AJAX* 即 *Asynchronous JavaScript and XML* (异步的JavaScript与XML技术),值的是一套综合了多项技术的浏览器端页面开发技术.Ajax的概念是由 /杰西.詹姆斯.贾瑞特/ 所提出。

 传统的web应用允许用户填写表单(form),当提交表单时就向服务器发送一个请求。服务器接并处理传来的表单 ，然后放回一个新的网页，这个做法浪费了许多带宽，因为在前后两个页面中的大部分HTML代码往往时相同的。由于每次应用
 都沟通都需要想服务器发送请求，应用的回应时间依赖于服务器的回应时间。这导致了用户界面的回应比本机应用要慢的多。

 与此不同，AJAX应用可以仅向服务器发送并取回必须的数据，并在客户端采用JavaScript处理来自服务器的回应。因为在服务器和浏览器之间交换的数据量减少，服务器回应更快了。同时，很多的处理工作可以在发出请求的客户端的浏览器上完成，因此web服务器的负荷也减少了。
asdfasdf
 上面时维基百科对Ajax的解释，我的想法是，在传统的web技术中，一般使用转发和重定向来实现网页的刷新，每次刷新都需要刷新整个页面，即使页面中改变的仅仅是一个字而已都需要重新刷新网页，最重要的是每次刷新都是需要后端服务器进行视图渲染（而大部分代码是重复的），浏览器只解析服务器发送过来的HTML页面，大部分工作都是在服务器上完成。而Ajax则打破了传统的web技术，利用JavaScript在前端完成一部分的工作，服务器只完成关键性的部分，例如：网页需要刷新，改动的仅仅是一段文字，服务器在这个过程中只需要将对应那一段文字发送给前端即可，既不需要进行视图渲染，又减少了HTML重复代码的传输，大大减少了服务器的压力，将一部分压力转到浏览器中，动态加载也让人机交互的体验更好。如果服务器的网络延迟非常好，基本能达到类似于本地应用的响应速度。


*** 优缺点
**** 优点：
使用Ajax的最大优点，就是能在不更新整个页面的前提下维护数据。这位是的Web应用程序更为迅捷的回应用户动作，并避免了在网络上发送那些没有改变的信息。
**** 缺点：
对应用Ajax最主要的批评就是，它可能破坏浏览器的后退和加入收藏书签功能。在动态更新页面的情况下，用户无法回到前一个页面状态，这是因为浏览器仅能几下历史记录中的 *静态页面* 。一个被完整读入的页面与一个已经被动态修改过的页面之间的可能差别非常微妙；用户通常都希望单击后退能够取消他们的前一次操作，当是在Ajax引用程序中，却无法这样做。 *不过现在已经又很多方法解决这个问题* 。
*** jQurey.ajax()
jQurey库中封装了ajax请求的方法。
jquery.ajax([settings])。发送请求并且的知成功还是失败。
+ type:类型，"POST"或者"GET",默认是"GET"。
+ url:发送请求的地址。
+ data：是一个对象，连同请求发送到服务器的数据。
+ dataType: 预期服务器放回的数据类型。如果不指定，jQurey将自动根据HTTP包含的MIME信息来智能判断，一般我们采用json个数，可以设置为"json"。
+ success:是一个方法，请求成功后返回的回调函数。传入返回后的数据，以及包含成功代码的字符串。
+ error: 是一个方法，请求失败时调用此函数。传入XMLHttpRqeuest对象。
*** 使用Ajax
使用之前先导入jQuery包，[[https://jquery.com/download/][Download]]将jquery放在statics/js目录下，这种方式导入时有可能会加载不到，使用另一种方式, 直接使用外部资源，在html中添加如下代码：
#+begin_src html
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
#+end_src
