#+TITLE: SpringBoot+security+jwt中使用BCryptPasswordEncoder对密码进行加密
#+AUTHOR: WUGUIPENG

* 简介
  现代的应用程序中，密码的安全都是及其重要的，它能保护用户的隐私，一旦密码明文泄露，是非常严重的，应为这个用户其他的网站可能使用了同样的密码或者相似的密码，这样的密码及其容易破解。
  
  在密码保护方面，用户尽可能的将密码设置的相对复杂，多个网站之间不能使用相同的密码或者相似的密码，可以使用密码管理器生成并保管密码，但是据我所知，目前没有多少人用，大部分的人都是使用同一个密码。所以这就需要应用程序对用户密码进行加密，这个加密时不可逆的。也就是说明文可以转换为密文，而密文不能反向推导出明文，但是在这里还存在一个问题，那就是使用相同的规则进行加密，同样的明文能得到同样的密文，这种也是不安全的。我们通常认为，密码明文只有用户知道，并且对同样的明文进行加密得到的密文也是不同的，并且不能逆向推导，这样的密码才是安全的。
  
  使用SpringSecurity中BCryptPasswordEncoder方法对密码进行加密（encode）和密码匹配（matches）。

  BCryptPasswordEncoder方法采用SHA-256+随机盐+密钥对密码进行加密，SHA是Hash算法，我们都知道Hash算法是不可逆的，并使用了随机盐（相同的明文能得到不同的密文）。

* 使用
  1. 在用户注册或者是将用户信息保存到数据库的时候，使用encode进行加密处理，这样保证数据库中的密码也是经过加密处理的。
  #+begin_src java
    public void insertUser(){
	String password = "123"; //模拟用户的密码

	BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
	String encode = encoder.encode(password); //加密处理
	User user = new User(2,"123", encode, "user");
	int i = userService.insertUser(user); // 保存到数据库中
	if (i > 0){
	    System.out.println("用户添加成功");
	}

    }
  #+end_src

  2. 在用户登入的时候，SpringSecurity会自动完成匹配，只需要在认证的时候传入 =BCryptPasswordEncoder()= 加密对象, 集成 =WebSecurityConfigurerAdapter= 类，并重写 =configure(AuthenticationManagerBuilder auth)= 方法。
     #+begin_src java
	   @Override
	   protected void configure(AuthenticationManagerBuilder auth) throws Exception {
	       auth.userDetailsService(userDetailsService).passwordEncoder(passwordEncoder());
	   }

	   @Bean
	   public BCryptPasswordEncoder passwordEncoder(){
	       return new BCryptPasswordEncoder();
	   }

     #+end_src
