#+TITLE: SpringBoot jwt

* JWT是什么
  JWT简称JSON Web Token,也就是通过JSON的形式作为Web应用中的令牌，用于各方之间安全的将信息作为JSON对象传输。数据传输过程中还可以完成数据加密，签名等相关处理。

* JWT能做什么

** 授权
   这是使用JWT最常见的方案。一旦用户登录，每个后续请求将包括JWT,从而允许用户访问该令牌允许的路由，服务和资源。单点登录是当今广泛使用JWT的一项功能，应为它的资源开销很小并且可以在不同的域中轻松使用。

** 信息交换
   JSON Web Token是在各方之间安全的传输信息的好方法。后端系统会检验发送过来的数据，不会盲目的使用这些数据，只有这些数据通过了数据检验，确保数据的安全性。

* JWT的优点
** 传统的Session认证方式
   http本身是一种无状态的协议，而这就意味着如果用户必须向携带 *用户名和密码* 进行用户认证，那么下次请求的时候， 还要进行用户认证，服务器并不知道是谁在请求，所以必须携带用户名和密码才能知道是谁在发起请求。为了解决这个问题，服务器需要存储一份登录信息，在用户登录的时候传递给浏览器，并保存为cookit，以便下次请求时携带这个信息请求服务器，此时服务器才知道是谁在请求，这就是基于传统的session请求。

*** 传统认证方式的问题
    1. 每个用户进行认证之后，服务端都会保存一份记录，这份记录是保存在内存中的，随着用户量的增加，服务端的开销会非常打。

    2. 不适用于微服务，应用程序使用微服务部署在多台服务器中，第一次认证在其中一台服务器中，并将请求信息保存在了这台服务器的内存中，但第二次请求的时候，可能请求的是另一台服务器，这台服务器中没有这个用户的登录信息，需要重新验证。

    3. 出于安全问题，cookie是可以被截获的，用户容易受到跨站请求伪造的攻击。

    4. 在前后端分离中页存在很多问题。

** JWT优势
   + 简洁：可以通过URL，POST参数或者HTTP header发送，因为数据量小，传输速度也很快.
   + 自包含： 负载中包含了用户所需的信息(不包括密码)，避免了多次查询数据库。
   + 因为Token是以JSON加密的形式保存在客户端的，所以JWT是跨语言的，原则上任何web心事都支持
   + 不需要在服务端保存会话信息，适用于分布式微服务。

* JWT的组成结构
** 令牌组成
   1. 标头（Header）
   2. 有效负载（Payload）
   3. 签名（Signature）
   JWT的结构由上面三部分组成，组成方式为： =Header.Payload.Signature= 使用点隔开。

** Header
   其中标头由两部分组成：令牌的类型和签名算法。
   #+begin_src json
     {
       "alg":"HS256",
       "typ":"JWT"
     }
   #+end_src
   对这个json对象进行Base64进行编码（Base64不是加密算法，因为所有人都可以对Base64进行解码的）就是令牌的标头。
** Payload
   令牌的第二部分是有效负载，其中包含了用户信息和其他的一些信息同样也会使用Base64进行编码，并组成令牌的第二部分。
   #+begin_src json
     {
       "sub":"543132",
       "name":"username",
       "admin": "true"
     }
   #+end_src

** Signature
   令牌的第三部分为签名，前两部分使用Base64进行编码，前端可以解码得到里面的信息。Signature需要使用编码后的header和payload以及我们提供的密钥，然后使用header中指定的签名算法进行签名。签名的作用是保证JWT没有被篡改过

* 验证的过程
  在服务端保存 *盐值* ，服务端发送给客户端一个令牌token，当客户端携带这个token将数据返回给服务端的时候，服务端会对这个token进行验证。验证的方法为：使用服务端的 *盐值*  + 客户端的 *Header* + *Payload* 得到一个签名，再将这个签名和客户端发过来的签名进行比对，比对成功验证通过，如果客户端发过来的数据中header和payload被篡改，签名是不可能认证成功的。
   
