#+TITLE: Redis Book
#+author: kunpeng
#+DATE: 2021-10-04

* redis特殊数据类型
** geospatial地理位置
朋友的定位,附近的人,距离计算等等;
Redis的Geo在Redis3.2版本就推出了!这个功能可以计算出地理位置信息,两地之间的距离和附近的人
只有六个命令
#+BEGIN_SRC shell
  GEOADD
  GEODIST
  GEOHASH
  GEOPOS
  GEORADIUS
  GEORADIUSBYMEMBER
#+END_SRC

#+BEGIN_SRC shell
  # 规则:两级无法直接添加, 一般下载城市经纬度数据,使用程序进行插入
  # 有效的经度-180到180
  # 有效的维度-85到85
  127.0.0.1:6379> geoadd china:city 113.88 22.55 shenzhen # 添加城市
  (integer) 1
  127.0.0.1:6379> geoadd china:city 113.01 25.78 chenzhou
  (integer) 1
  127.0.0.1:6379> geoadd china:city 112.98 28.25 changsha
  (integer) 1
  127.0.0.1:6379> geopos china:city shenzhen  # 获取地理信息
  1) 1) "113.87999922037124634"
     2) "22.5500010475923105"
  127.0.0.1:6379> geopos china:city chenzhou
  1) 1) "113.0099979043006897"
     2) "25.7799987556591006"
  127.0.0.1:6379> geopos china:city changsha
  1) 1) "112.9800000786781311"
     2) "28.25000087963665152"
  127.0.0.1:6379> geopos china:city changsha chenzhou
  1) 1) "112.9800000786781311"
     2) "28.25000087963665152"
  2) 1) "113.0099979043006897"
     2) "25.7799987556591006"
  # GEODIST给定两地的经纬度信息可以计算出两地之间的距离,单位如下:
  # m 表示单位为米。
  # km 表示单位为千米。
  # mi 表示单位为英里。
  # ft 表示单位为英尺。
  127.0.0.1:6379> GEODIST china:city chenzhou changsha km # 查询两地的距离
  "274.7453"
  127.0.0.1:6379> GEODIST china:city chenzhou shenzhen km
  "369.9454"
  # georadius 可以根据经纬度的中心查看包含在这个区域的其他地理位置信息
  # 指定经纬度和半径距离,查找出周围的位置,这个位置必须在集合中
  127.0.0.1:6379> GEORADIUS china:city 110 30 100 km 
  (empty array)
  127.0.0.1:6379> GEORADIUS china:city 110 30 500 km
  1) "changsha"
  # 还可以指定查找出来的数量
  127.0.0.1:6379> GEORADIUS china:city 110 30 500 km withdist withcoord count 1
  1) 1) "changsha"
     2) "348.8645"
  3) 1) "112.9800000786781311"
  2) "28.25000087963665152"
  # 根据元素的地理信息查找出其他元素是否在附近
  127.0.0.1:6379> GEORADIUSBYMEMBER china:city chenzhou 400 km
  1) "shenzhen"
  2) "chenzhou"
  3) "changsha"
  # geohash 返回一个或者多个位置元素的geohash表示 *用的较少*
  127.0.0.1:6379> geohash china:city chenzhou shenzhen
  1) "ws86et577u0"
  2) "ws0br3hgk20"
  # geo底层实现原理其实就是Zset, 可以使用Zset操作geo
  127.0.0.1:6379> ZRANGE china:city 0 -1
  1) "shenzhen"
  2) "chenzhou"
  3) "changsha"
  127.0.0.1:6379> ZREM china:city changsha
  (integer) 1
  127.0.0.1:6379> ZRANGE china:city 0 -1
  1) "shenzhen"
  2) "chenzhou"
#+END_SRC

** hyperloglog
*** 基数
A{1,3,5,7,8,7}
B{1,3,5,7,8}
基数(不重复的元素) = 5,可以接受误差
*** 简介
redis2.8.9版本添加了hyperloglog数据结构.
redis hyperloglog 基数统计算法!
*网页的UV(一个人访问一个网站多次,但是还是一个人).*
传统的方式,set保存用户id,set中的元素不能够重复,然后就可以统计set中的元素数量作为判断标准.
这个方式如果保存大量的用户id,就会比较麻烦,我们的目的是为了计数,而不是保存用户id.
*优点: 占用的内存是固定的,2^64 不同的元素的基数,只花费12kb内存,如果要从内存的角度来比较的话hyperloglog首选*
0.81%错误率! 统计UV任务,可以忽略不计!

*** 使用
#+begin_src shell
  127.0.0.1:6379> pfadd pf a b c d e f j h i j # 添加元素
  (integer) 1
  127.0.0.1:6379> pfcount pf  # 统计元素个数
  (integer) 9
  127.0.0.1:6379> pfadd pf2 i j k l m n o p q # 添加元素
  (integer) 1
  127.0.0.1:6379> pfcount pf2
  (integer) 9
  127.0.0.1:6379> pfmerge pf3 pf pf2 # 合并两个key
  OK
  127.0.0.1:6379> pfcount pf3 # 查看合并后key的个数
  (integer) 16
#+end_src
如果允许容错,可以使用hyperloglog
如果不允许容错,那就需要使用set集合
** bitmaps
*** 位存储
统计疫情感染人数: 0 1 0 0 0 0
未感染为0, 感染为1
统计用户信息,活跃,不活跃,登录,未登录等两个状态的都可以使用bitmaps,这就是bitmaps的应用场景!
*** 使用
#+BEGIN_SRC shell
  # 模拟每周打卡,1代表打卡,0代表未打卡,数字0到6代表一周的每一天
  # 将这样一组数据使用setbit添加到bitmaps中.
  127.0.0.1:6379> setbit sign 0 1
  (integer) 0
  127.0.0.1:6379> setbit sign 1 1
  (integer) 0
  127.0.0.1:6379> setbit sign 2 1
  (integer) 0
  127.0.0.1:6379> setbit sign 3 1
  (integer) 0
  127.0.0.1:6379> setbit sign 4 1
  (integer) 0
  127.0.0.1:6379> setbit sign 5 0
  (integer) 0
  127.0.0.1:6379> setbit sign 6 0
  (integer) 0
  # 获取每天的打卡情况,打卡成功返回1,打卡失败返回0
  127.0.0.1:6379> getbit sign 0
  (integer) 1
  127.0.0.1:6379> getbit sign 2
  (integer) 1
  127.0.0.1:6379> getbit sign 6
  (integer) 0
  127.0.0.1:6379>
  # 统计一周打卡次数
  127.0.0.1:6379> BITCOUNT sign
  (integer) 5
  127.0.0.1:6379>
#+END_SRC

* 事物
** redis事物
*** 简介
*原子性:要么同时成功,要么同时失败!*
Redis单条命令是保证原子性的,但是redis事物是不保证原子性的.
/Redis事物的本质:一组命令的集合!一个事物中的所有命令都会被序列化,在事物的执行过程中,会按照孙需执行!/
*一次性,顺序性,排他性!执行一系列的命令!*
*Redis事物中没有隔离级别的概念!*
所有的命令在事物中,并没有直接被执行!只有发起执行命令的时候才执行!Exec
*** redis事物
**** 开启事物(multi)
#+begin_src shell
  127.0.0.1:6379> MULTI
  OK
#+end_src
**** 命令入队(...)
#+begin_src shell
  127.0.0.1:6379(TX)> set k1 v1
  QUEUED
  127.0.0.1:6379(TX)> set k2 v2
  QUEUED
  127.0.0.1:6379(TX)> get k2
  QUEUED
  127.0.0.1:6379(TX)> set k3 v3
  QUEUED
#+end_src
**** 执行事物(exec)
#+begin_src shell
  127.0.0.1:6379(TX)> exec
  1) OK
  2) OK
  3) "v2"
  4) OK
#+end_src
**** 放弃事物(discard)
#+begin_src shell
  127.0.0.1:6379(TX)> DISCARD
  OK
#+end_src
**** 编译型异常
(代码有问题,命令报错),事物中所有的命令都不会被执行
#+begin_src shell
  127.0.0.1:6379> MULTI
  OK
  127.0.0.1:6379(TX)> set k1 v1
  QUEUED
  127.0.0.1:6379(TX)> set k2 v3
  QUEUED
  127.0.0.1:6379(TX)> set k3 v2
  QUEUED
  127.0.0.1:6379(TX)> getset k3 # 错误的命令
  (error) ERR wrong number of arguments for 'getset' command
  127.0.0.1:6379(TX)> set k4 v4
  QUEUED
  127.0.0.1:6379(TX)> set k5 v5
  QUEUED
  127.0.0.1:6379(TX)> exec # 执行事物报错
  (error) EXECABORT Transaction discarded because of previous errors.
  127.0.0.1:6379> get k1 # 所有的命令都不会被执行
  (nil)
#+end_src
**** 运行时异常
如果事物队列中存在语法性错误,那么在执行的时候,其他命令可以正常的执行,错误命令抛出异常
#+begin_src shell
  127.0.0.1:6379> set k1 "v1" # set一个字符串
  OK
  127.0.0.1:6379> MULTI # 开启事物
  OK
  127.0.0.1:6379(TX)> INCR k1 # 字符串自增,在编译时不会报错
  QUEUED
  127.0.0.1:6379(TX)> set k2 v2
  QUEUED
  127.0.0.1:6379(TX)> set k3 v3
  QUEUED
  127.0.0.1:6379(TX)> get k3
  QUEUED
  # 执行事物,即使事物中的某一条语句执行失败,抛出异常,也不会影响其他命令的执行
  127.0.0.1:6379(TX)> exec 
  1) (error) ERR value is not an integer or out of range
  2) OK
  3) OK
  4) "v3"
#+end_src
*** 锁
**** 悲观锁
很悲观,什么时候都会出现问题,无论做什么都会加锁,导致性能降低.
**** 乐观锁
很乐观,认为什么时候都不会出向问题,所以不会加锁,更新数据的时候去判断一下,在此期间是否有人修改这个数据.
获取version
更新的时候比较version
**** redis监视测试
#+begin_src shell
  # 线程1
  127.0.0.1:6379> set m 100 # 设置money为100
  OK
  127.0.0.1:6379> set o 0 # 设置支出为0
  OK
  127.0.0.1:6379> watch m #监视money
  OK
  127.0.0.1:6379> MULTI # 开启事物
  OK
  127.0.0.1:6379(TX)> decrby m 20
  QUEUED
  127.0.0.1:6379(TX)> incrby o 20
  QUEUED
  127.0.0.1:6379(TX)> exec # 执行事物
  1) (integer) 80
     2) (integer) 20

        # 线程2
        127.0.0.1:6379> WATCH m # 线程2开始监控money
        OK
        127.0.0.1:6379> MULTI # 开启事物
        OK
        127.0.0.1:6379(TX)> DECRBY m 10
        QUEUED
        127.0.0.1:6379(TX)> INCRBY o 10 # 这里还没有执行事物

        # 线程1
        127.0.0.1:6379> get m
        "80"
        127.0.0.1:6379> set m 1000 # 线程1改变了money的值
        OK
        127.0.0.1:6379>

        # 线程2
        # 线程2开始执行事物,可以看到返回nil,代表执行失败.
        # watch会监控money的值是否改变
        # 如果money的值被其他线程改变了,那么事物一定会执行失败
        127.0.0.1:6379(TX)> exec 
        (nil)

        # 当线程1改变了money的值之后.
        # 线程2需要先取消监视,对线程1改变后的值进行重新监视即可
        127.0.0.1:6379> UNWATCH # 取消监视
        OK
        127.0.0.1:6379> WATCH m # 重新监视
        OK
        127.0.0.1:6379> MULTI
        OK
        127.0.0.1:6379(TX)> DECRBY m 10
        QUEUED
        127.0.0.1:6379(TX)> INCRBY o 10
        QUEUED
        127.0.0.1:6379(TX)> exec # 执行事物
        1) (integer) 990
           2) (integer) 30
#+end_src

* Jedis
** 创建Maven项目
*** 导入对应的依赖
#+begin_src xml
  <dependencies>
    <dependency>
      <groupId>redis.clients</groupId>
      <artifactId>jedis</artifactId>
      <version>3.2.0</version>
    </dependency>

    <dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>fastjson</artifactId>
      <version>1.2.62</version>
    </dependency>
  </dependencies>
#+end_src
*** 编码测试:
+ 连接数据库
+ 操作命令
+ 断开连接
  #+begin_src java
    package com.kunpeng;

    import redis.clients.jedis.Jedis;

    public class Testping {
        public static void main(String[] args) {
            Jedis jedis = new Jedis("127.0.0.1",6379);
            String ping = jedis.ping();
            System.out.println(ping); // PONG
        }
    }
  #+end_src
*** 常用API
所有aip命令都合之前学习的命令一样
**** String
**** List
**** Set
**** Hash
**** Zset
*** 事物
#+begin_src java
  public static void main(String[] args) {
      Jedis jedis = new Jedis("127.0.0.1",6379); // 连接数据库
      jedis.flushDB();
      JSONObject jsonObject = new JSONObject();

      jsonObject.put("hello","word");
      jsonObject.put("name","wugupeng");

      Transaction multi = jedis.multi();//开启事物
      String result = jsonObject.toJSONString();
      try{
          multi.set("user1",result);
          multi.set("user2",result);
          int i = 1/0;
          multi.exec(); //执行事物
      } catch (Exception e){
          multi.discard();  //放弃事物
          e.printStackTrace();
      } finally {
          System.out.println(jedis.get("user1"));
          System.out.println(jedis.get("user2"));
          jedis.close(); //关闭连接
      }
  }
#+end_src

* SpringBoot 整合
** 简介
+ SpringBoot操作数据: spring-data jpa jdbc mangodb redis!
+ SpringData也是和SpringBoot齐名的项目!
+ 说明: 在SpringBoot2.x之后,原来使用jedis被替换为了lettuce
+ jedis: 采用直连,多个线程操作的话,是 *不安全* 的,如果要避免不安全问题,使
  用redis pool连接池,BIO模式
+ lettuce: 采用netty,实力可以在多个线程中进行共享, *不存在线程不安全* 的情
  况, NIO模式!
** 源码分析
#+begin_src java
      @Bean
      @ConditionalOnMissingBean(name = {"redisTemplate"}) //可以自己定义一个redisTemplate替换这个redisTemplate
      @ConditionalOnSingleCandidate(RedisConnectionFactory.class)
      public RedisTemplate<Object, Object> redisTemplate(RedisConnectionFactory redisConnectionFactory) {
          // 默认的RedisTenplate 没有过多的设置,redis对象都是需要序列化的
          // 两个泛型都是Object类型,后面需要进行强制转换<String,Object>
          RedisTemplate<Object, Object> template = new RedisTemplate();
          template.setConnectionFactory(redisConnectionFactory);
          return template;
      }

      @Bean
      @ConditionalOnMissingBean
      @ConditionalOnSingleCandidate(RedisConnectionFactory.class)
      // 由于String类型是redis最常使用的类型
      public StringRedisTemplate stringRedisTemplate(RedisConnectionFactory redisConnectionFactory) {
          StringRedisTemplate template = new StringRedisTemplate();
          template.setConnectionFactory(redisConnectionFactory);
          return template;
      }

#+end_src

* redis持久化
** 简介
+ 面试和工作，持久化都是重点
+ Redis是内存数据库，如果不将内存中的数据库保存到磁盘上，
  一旦服务器程序退出，服务器中的数据库状态也会消失，所以Redis提供了持久化功能
** RDB（Redis DataBase）
*** 什么是RDB
在指定的时间间隔内将内存中的数据集快照写入磁盘，它恢复是是将快照文件直接读取到内存中。
Redis会单独创建（fork）一个子进程类进行持久化，先将数据写入到一个临时文件中，待持久化过程都结束了，
再用这个临时文件替换上次持久化之后的文件。整个过程中，主进程是不进行任何IO操作的。这就确保了Redis极高的性能。
如果需要进行大规模数据的恢复，且对于数据恢复的完整性不是非常敏感，那RDB方式要比AOF方式更加的高效。
RDB的缺点是最后一次持久化后的数据可能对视。redis默认使用的就是RDB，一般情况下不需要修改这个配种。

*rdb保存的文件是dump.rdb* 配置文件中默认的，可通过配置文件修改

**** 出发rdb规则
+ save的规则满足的情况下，会自动触发rdb规则
+ 执行flushall命令，也会触发rdb规则
+ 推出redis，也会触发rdb规则
*触发rdb规则就会生成一个dump.rdb文件*
**** 恢复rdb文件
+ 只需要将rdb文件放在redis默认路径，在redis启动的时候会自动检查改文件
**** 优点
+ 适合大规模的数据恢复
+ 对数据的完整性要求不高
**** 缺点
+ 需要一定的时间间隔进行操作！如果redis意外宕机，最后一次修改的数据可能会丢失
+ fork进程会占用一定的内存
** AOF（Append Only File）
*** 简介
将命令执行都记录下来，history，恢复的时候将这些命令重新执行一遍，用于恢复数据
以日志的形式记录每一个错做，将Redis执行过的所有命令记录下载（读取操作不记录），只许追加文件但不可以改写文件，
redis启动之初会读取改文件重新构建数据。 *redis默认是关闭的，需要手动开启*

*AOF保存的是appendonly.aof文件* 可通过配置进行修改

*** 优点
+ 每一次修改都会同步，文件完整性更好，效率最低
+ 每秒同步一次，可能会丢失一秒的数据，效率中等
+ 从不同步，效率最高

*** 缺点
+ 相对于数据文件来说，aof要比rdb文件更大，修复速度页比rdb慢
+ aof运行效率也比rdb慢，所以redis默认使用的是rdb

* redis发布订阅
* redis主从复制
** 环境搭建
三台服务器：rn.kunpeng.ga cloud.kunpeng.ga orcale.kunpeng.ga。
三台服务器正常运行redis-server,并开发6379端口，保证能够实现远程访问。
rn.kunpeng.ga这台服务器作为主机，orcale.kunpeng.ga orcale.kunpeng.ga 这两台服务器作为从机
#+begin_src bash
  # rn.kunpeng.ga
  # 查看主机和从机，这里的输出是已经配置好主机和从机的配置
  127.0.0.1:6379> info replication 
  # Replication
  role:master   # master主机
  connected_slaves:2 # 这里代表的是从机的数量
  slave0:ip=146.56.134.137,port=6379,state=online,offset=42,lag=0
  slave1:ip=146.56.151.86,port=6379,state=online,offset=42,lag=1
  master_replid:b73ec61d08a134a26c7429ab2c482d4cc8030cfc
  master_replid2:0000000000000000000000000000000000000000
  master_repl_offset:42
  second_repl_offset:-1
  repl_backlog_active:1
  repl_backlog_size:1048576
  repl_backlog_first_byte_offset:1
  repl_backlog_histlen:42

  # orcale.kunpeng.ga
  127.0.0.1:6379> SLAVEOF rn.kunpeng.ga 6379
  OK

  # cloud.kunpeng.ga
  127.0.0.1:6379> SLAVEOF rn.kunpeng.ga 6379
  OK


  # 测试
  # rn.kunpeng.ga
  127.0.0.1:6379> set cloud ok
  OK
  127.0.0.1:6379> set orcale ok
  OK

  # orcale.kunpeng.ga
  127.0.0.1:6379> get orcale
  "ok"

  # cloud.kunpeng.ga
  127.0.0.1:6379> get cloud
  "ok"

#+end_src
** 概念
主从复制，是指将一台redis服务器的数据，复制到其他的redis服务器。
前者称为主节点（master/leader），后者称为从节点（slave/follower）；
 *数据复制是单向的，只能从主节点到从节点。* master以写为主，slave以读为主。
 且一个主节点可以有多个从节点（或者没有从节点），但一个从节点智能有一个主节点。
**** 主从复制的朱永主要包括：
+ 数据冗余：主从复制实现了数据的热备份，是持久化之外的一种数据冗余方式。
+ 故障恢复：当主节点出现问题，可以由从节点提供服务，实现快速的故障恢复；实际上是一种服务的冗余。
+ 负载均衡：在主从复制的基础上，配合对鞋分离，可以由主节点提供写服务，有从节点提供读服务，
  分担服务器负载；尤其实在写少读多的场景，通过多个从节点分担读负载，可以大大提高redis服务器的并发量。
+ 高可用（集群）基石：除了上述作用以外，主从复制还是哨兵和集群能够实施的基础，因此说主从复制是redis高可用的基础。
* 哨兵模式
自动选举主节点
** 简介
参考文章： [[https://www.jianshu.com/p/252df87af1ae][redis哨兵模式实战]]
 
主从切换技术的方法是：当主服务器宕机后，需要手动把一台从服务器切换为主服务器，这就需要人工干预，费事费力。
还会造成一段时间内服务不可用。这不是一种推荐的方式，更多的时候，我们优先考虑哨兵模式。
Redis2.8开始正式提供了Sentinel（哨兵模式）架构来解决这个问题。
哨兵模式是一种特殊的模式，首先redis提供了哨兵的命令，哨兵是一个独立的进程，作为进程，它会独立运行。
其原理是 *哨兵通过发送命令，等待redis服务器响应，从而监控运行多个redis实例。*

*哨兵有两个作用：*
+ 通过发送命令，让redis服务器返回监控其运行状态，保留主服务器和从服务器
+ 当哨兵检测到master宕机，会自动将slave切换为master，然后通过 *发布订阅模式* 通知其他从服务器，修改配置文件，让他们切换主机。

然而一个哨兵进程对Redis服务器进行监控，可能会出现问题，为此，我们可以使用多个哨兵进行监控。各个哨兵之间还会进行监控，这样就形成了多哨兵模式。

用文字描述一下故障切换（failover）的过程。

假设主服务器宕机，哨兵1先检测到这个结果，系统并不会马上进行failover过程，仅仅是哨兵1主观的认为主服务器不可用，这个现象成为主观下线。当后面的哨兵也检测到主服务器不可用，并且数量达到一定值时，那么哨兵之间就会进行一次投票，投票的结果由一个哨兵发起，进行failover操作。切换成功后，就会通过发布订阅模式，让各个哨兵把自己监控的从服务器实现切换主机，这个过程称为客观下线。这样对于客户端而言，一切都是透明的。



* redis缓存穿透和雪崩
** 简介
redis缓存的作用，极大的提升了应用程序的性能和效率，特别是数据查询方面。但同时，它也带来了一些问题。
其中，最大的问题就是数据的一致性的问题，从严格意义上讲，这个问题无解。如果对数据的一致性要求很高，那么就不能使用缓存。
另外一些经典的问题就是缓存穿透，缓存雪崩和缓存击穿。目前，业界都有比较流行的解决方法。
** 缓存穿透
*** 概念
缓存穿透的概念很简单，用户想要查询一个数据，发现redis内存数据库没有，也就是缓存没有命中，于是向持久层数据库查询。发现也没有，于是查询失败。当用户很多的时候，缓存都没有命中，于是都去请求了持久层数据库。这会给持久层数据库造成很大的压力，这时候就相当于出现了缓存穿透。
*** 布隆过滤器
布隆过滤器是一种数据结构，对所有可能查询的参数以hash形式存储，在控制层先进行校验，不符合则丢弃，从而避免了对底层存储系统的查询压力；
*** 缓存空对象
当存储不命中后，及时返回的空对象也将其缓存起来，同时会设置一个过期时间，之后再访问这个数据会从缓存中获取，保护了后端数据源；
*但是这种方法会存在两个问题：*
 + 如果控制对象别缓存起来，这就意味着缓存需要更多的空间存储更多的键，因为这当中可能会有很多的空值的键！
 + 及时对空值设置了过期时间，还是对存在缓存层和存储层的数据会有一段时间窗口的不一致，这对于需要保持一致性的业务会有影响。
** 缓存击穿
*** 概述
这里需要注意和缓存穿透的区别，缓存击穿，是指一个key非常热点，再不停的扛着大并发，大并发集中对这一个点进行访问，当这个key再失效的瞬间，持续的大并发就穿破缓存，直接请求数据库，就像再屏障上开凿了一个洞。
当某个key再过期的瞬间，大量的请求并发访问，这类数据一般是热点数据，由于缓存过期，同时访问数据库来查询最新数据，并且放回写缓存，会导致数据库瞬间压力过大。
*** 解决方法
**** 设置热点数据不过期
从缓存层面来看，没有设置过期时间，所以不会存在热点key过期后产生的问题。
**** 加互斥锁
分布式锁：使用分布式锁，保证对每个key同时只有一个线程去查询后端数据，其他线程没有获得分布式锁的权限，因此只需要等待即可。这种方式将高并发的压力转移到了分布式锁，因此对分布式锁的考研很大。

** 缓存雪崩
*** 概念
缓存雪崩，是指再某一时段内，缓存集中过期失效。
产生雪崩的原因之一，比如秒杀活动，商品比较集中的放入缓存，假设缓存一个小时，一个小时后这批商品的缓存就都过期了。而对这批商品的访问查询，都落到了数据库上，对于数据库而言，就会产生周期性的压力风波。于是所有的请求都会达到存储层，存储层的调用量暴增，会造成存储层也崩掉的情况。

再实际中，集中过期并不是致命的，致命的是缓存雪崩，是缓存服务器某个节点宕机或者断网。因为自然形成的缓存雪崩，一定是再某个时间段集中创建缓存，这个时候，数据库也是可以顶住压力的。无非是对数据库产生周期性的压力而已。二缓存服务节点宕机，对数据库服务造成的压力是不可预知的，很有可能瞬间就把数据库压块。

*** 解决方案
**** redis高可用
这个思想的含义是，既然redis有可能宕机，就对增设几台redis服务器，这样一台宕机之后其他的还可以继续工作。
**** 限流降级
这个解决方案的思想是，再缓存失效后，通过枷锁或者队列来控制读大户巨款写缓存的线程数量。比如对某个key只允许一个线程查询和读写缓存，其他线程等待。
**** 数据预热
数据加热的含义就是再正式部署之前，我先把可能的数据先预先访问一边，这样部分可能大量访问的数据库就会加载到缓存中。再即将发生大并发访问钱手动触发加载缓存不同的key，设置不同的过期时间，让缓存事项的时间点尽量均匀。
