#+TITLE: SSM整合

* SSM
** 整合Spring SpringMVC Mybatis
*** 环境要求
+ IDEA
+ MySql 8.0
+ Tomcat 9.0
+ Maven 3.6
*** 数据库环境
准备数据库
#+begin_src sql
  create database `ssmbuild`;

  use `ssmbuild`;

  create table `books`(
         `bookid` int(10) not null auto_increment comment '书id',
         `bookname` varchar(100) not null comment '书名',
         `bookCounts` int(11) not null comment '数量',
         `detail` varchar(200) not null comment '描述',
         key `bookid` (`bookid`)
  )engine=innodb default charset=utf8

  insert into `books` (`bookid`,`bookname`,`bookcounts`,`detail`) values
  (1,'Java',1,'从入门到放弃'),
  (2,'Mysql',10,'从删库到跑路'),
  (3,'Linux',5,'从进门到牢底坐穿');
#+end_src
*** idea创建项目导入依赖
使用idea创建一个空的Maven项目,在pom.xml中导入下面的依赖.
#+begin_src xml
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.2</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
      <version>5.1.49</version>
    </dependency>

    <dependency>
      <groupId>com.mchange</groupId>
      <artifactId>c3p0</artifactId>
      <version>0.9.5.2</version>
    </dependency>

    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>servlet-api</artifactId>
      <version>2.5</version>
    </dependency>

    <dependency>
      <groupId>javax.servlet.jsp</groupId>
      <artifactId>jsp-api</artifactId>
      <version>2.2</version>
    </dependency>

    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>jstl</artifactId>
      <version>1.2</version>
    </dependency>

    <dependency>
      <groupId>org.mybatis</groupId>
      <artifactId>mybatis-spring</artifactId>
      <version>2.0.6</version>
    </dependency>

    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-webmvc</artifactId>
      <version>5.3.10</version>
    </dependency>

    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-jdbc</artifactId>
      <version>5.3.10</version>
    </dependency>
  </dependencies>
#+end_src
*** 静态资源导出问题
在pom.xml的dependencies下面添加如下代码
#+begin_src xml
  <build>
    <resources>
      <resource>
        <directory>src/main/java</directory>
        <includes>
          <include>**/*.properties</include>
          <include>**/*.xml</include>
        </includes>
        <filtering>false</filtering>
      </resource>
      <resource>
        <directory>src/main/resources</directory>
        <includes>
          <include>**/*.properties</include>
          <include>**/*.xml</include>
        </includes>
        <filtering>false</filtering>
      </resource>
    </resources>
  </build>
#+end_src
*** 建立基本的结构和配置框架
+ com.kunpeng.dao
+ com.kunpeng.pojo
+ com.kunpeng.service
+ com.kunpeng.controller
+ mybatis-config.xml
  #+begin_src xml
    <?xml version="1.0" encoding="utf-8" ?>
    <!DOCTYPE configuration
            PUBLIC "-//mybatis.org//DTD Config 3.0//EN"
            "http://mybatis.org/dtd/mybatis-3-config.dtd">

    <configuration>

    </configuration>
  #+end_src
+ applicationContext.xml
  #+begin_src xml

    <?xml version="1.0" encoding="UTF-8"?>
    <beans xmlns="http://www.springframework.org/schema/beans"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:context="http://www.springframework.org/schema/context"
           xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans.xsd
        http://www.springframework.org/schema/context
        http://www.springframework.org/schema/context/spring-context.xsd">

    </beans>
  #+end_src
*** Mybatis
mybatis-config.xml配置文件使用来配置 ~mybatis~ 的.

在mybatis-config.xml配置文件中配置别名, 添加在configuration元素中.
#+begin_src xml
  <configuration>
      <typeAliases>
          <package name="com.kunpeng.pojo"/>
      </typeAliases>
  </configuration>
#+end_src
*** 创建实体类
在 ~pojo~ 下面创建 ~Books.java~ 实体类, 对应数据库中的字段.
#+begin_src java
  @Data
  @AllArgsConstructor
  @NoArgsConstructor
  public class Books {
      private int bookId;
      private String bookName;
      private int bookCount;
      private String detail;
  }
#+end_src
这里使用了lombok简化了实体类
*** 配置dao层
在 ~com.kunpeng.dao~ 下创建 ~BooksMapper.java~ 文件,并添加以下内容.
#+begin_src java
  public interface BookMapper {
      //添加一本书
      int addBook(Books books);
      //删除一本书
      int deleteBook(int bookId);
      //更新一本书
      int updateBook(Books books);
      //查询一本书
      Books queryBookById(int bookId);
      //查询all
      List<Books> queryAllBook();

  }
#+end_src
*** 配置数据库连接
在 ~resources~ 目录下创建 ~database.properties~ 配置文件, 并添加连接数
据库配置.
#+begin_src text
  jdbc.driver=com.mysql.jdbc.Driver
  jdbc.url=jdbc:mysql://rn.kunpeng.ga:3306/ssmbuild
  jdbc.username=kunpeng
  jdbc.password=wuguipeng
#+end_src

- jdbc.driver :: 配置数据库驱动
- jdbc.url :: 配置数据库连接地址端口等.
- jdbc.username :: 数据库用户名
- jdbc.password :: 数据库密码
*** 配置数据源
在 ~resources~ 目录下创建 ~spring-dao.xml~ 配置文件,并添加以下内容.
#+begin_src xml
  <?xml version="1.0" encoding="UTF-8"?>
  <beans xmlns="http://www.springframework.org/schema/beans"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:context="http://www.springframework.org/schema/context"
         xsi:schemaLocation="http://www.springframework.org/schema/beans
                             http://www.springframework.org/schema/beans/spring-beans.xsd http://www.springframework.org/schema/context https://www.springframework.org/schema/context/spring-context.xsd">

      <!--1. 关联数据库配置-->
      <context:property-placeholder location="classpath:database.properties"/>
      <!--2.连接池
          dbcp:半自动化,不能自动连接
          c3p0:自动化操作,自动化的加载配置文件,并且自动设置到对象中!
          druid:
          hikari:
      -->
      <bean id="dataSource" class="com.mchange.v2.c3p0.ComboPooledDataSource">
          <property name="driverClass" value="${jdbc.driver}"/>
          <property name="jdbcUrl" value="${jdbc.url}"/>
          <property name="user" value="${jdbc.username}"/>
          <property name="password" value="${jdbc.password}"/>

  <!--        c3p0连接池的私有属性-->
          <property name="maxPoolSize" value="30"/>
          <property name="minPoolSize" value="10"/>
          <property name="autoCommitOnClose" value="false"/>
          <property name="checkoutTimeout" value="10000"/>
          <property name="acquireRetryAttempts" value="2"/>
      </bean>
      <!--3.sqlSessionFactory-->

      <bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
          <property name="dataSource" ref="dataSource"/>
          <property name="configLocation" value="classpath:mybatis-config.xml"/>
      </bean>

  <!--    4.配置dao接口扫描包,动态的实现了Dao接口可以注入到spring容器中-->
      <bean class="org.mybatis.spring.mapper.MapperScannerConfigurer">
  <!--        注入 sqlSessionFactory-->
          <property name="sqlSessionFactoryBeanName" value="sqlSessionFactory"/>
  <!--        扫描dao包-->
          <property name="basePackage" value="com.kunpeng.dao"/>
      </bean>
  </beans>
#+end_src
*** 查询数据库
配置好 ~dao~ 层,数据库连接,就可以编写sql语句, 在 ~resources/mapper~ 目
录下创建 ~BookMapper.xml~ 文件,这个对应 ~dao~ 层中的 ~BookMapper.java~
文件, ~BookMapper.java~ 中定义了5个业务接口, ~BookMapper.xml~ 中实现了
5个业务的具体sql语句.
#+begin_src xml
  <?xml version="1.0" encoding="utf-8" ?>
  <!DOCTYPE mapper
          PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
          "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
  <mapper namespace="com.kunpeng.dao.BookMapper">
      <insert id="addBook" parameterType="books">
          insert into ssmbuild.books (bookname,bookcount,detail)
          values (#{bookName},#{bookCount},#{detail});
      </insert>

      <delete id="deleteBookById" parameterType="int">
          delete from ssmbuild.books where bookid=#{bookId}
      </delete>

      <update id="updateBook" parameterType="books">
          update ssmbuild.books set
          bookname=#{bookName}, bookCount=#{bookCount},detail=#{detail}
          where bookid=#{bookId}
      </update>

      <select id="queryBookById" parameterType="int" resultType="books">
          select * from ssmbuild.books where booid=#{bookId}
      </select>

      <select id="queryAllBook" resultType="books">
          select * from ssmbuild.books
      </select>

  </mapper>
#+end_src
完成上面代码之后,在 ~mybatis-config.xml~ 配置文件中注册
~BookMapper.xml~ 在 ~mapper~ 元素中指定 ~BookMapper.xml~ 的路径.
#+begin_src xml
  <configuration>
      <typeAliases>
          <package name="com.kunpeng.pojo"/>
      </typeAliases>
      <mappers>
          <mapper resource="mapper/BookMapper.xml"/>
      </mappers>
  </configuration>
#+end_src

*** 编写业务层(service)
在 ~service~ 目录下创建 ~BooksService.java~ 文件. 并添加以下内容.
#+begin_src java
  public interface BooksService {
      //添加一本书
      int addBook(Books books);
      //删除一本书
      int deleteBook(int bookId);
      //更新一本书
      int updateBook(Books books);
      //查询一本书
      Books queryBookById(int bookId);
      //查询all
      List<Books> queryAllBook();
  }
#+end_src
~BooksService.java~ 文件和 ~BookMapper.java~ 文件虽然没有任何区别. 但
是非常有必要的.

在 ~service~ 目录下创建实现类 ~BooksServiceImpl.java~ 文件, 继承
~BookService~ 接口并实现所有方法,在方法中调用 ~dao~ 层中的
~BookMapper.java~ 中的业务.
#+begin_src java
  public class BooksServiceImpl implements BooksService{
      //service 调dao层


      private BookMapper bookMapper;
      public void setBookmapper(BookMapper bookmapper) {
          this.bookMapper = bookmapper;
      }

      @Override
      public int addBook(Books books) {
          return bookMapper.addBook(books);
      }

      @Override
      public int deleteBook(int bookId) {
          return bookMapper.deleteBook(bookId);
      }

      @Override
      public int updateBook(Books books) {
          return bookMapper.updateBook(books);
      }

      @Override
      public Books queryBookById(int bookId) {
          return bookMapper.queryBookById(bookId);
      }

      @Override
      public List<Books> queryAllBook() {
          return bookMapper.queryAllBook();
      }


  }
#+end_src

完成上面的代码之后,需要将 ~service~ 层的内容注册到 ~bean~ 中,在
~resources~ 目录下创建 ~spring-service.xml~ 配置文件,并添加以下内容.
#+begin_src xml
  <?xml version="1.0" encoding="UTF-8"?>
  <beans xmlns="http://www.springframework.org/schema/beans"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:context="http://www.springframework.org/schema/context"
         xsi:schemaLocation="http://www.springframework.org/schema/beans
                             http://www.springframework.org/schema/beans/spring-beans.xsd
                             http://www.springframework.org/schema/context
                             https://www.springframework.org/schema/context/spring-context.xsd">
  <!--    1.扫描service下的包-->
      <context:component-scan base-package="com.kunpeng.service"/>
  <!--    2.将所有业务类,注入到spring,可以通过配置,或者注解实现-->
      <bean id="booksServiceImpl" class="com.kunpeng.service.BooksServiceImpl">
          <property name="bookmapper" ref="bookMapper"/>
      </bean>
  <!--    3.事物-->
      <bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
  <!--        注入数据源-->
          <property name="dataSource" ref="dataSource"/>

      </bean>
  </beans>
#+end_src

*** 测试数据库是否配置成功
每次完成配置之后都需要测试是否配置成功,不要等到全部配置完成之后再测试,
配置越多,错误越多,越难排错.

首先将这些配置注册到 ~~applicationContext.xml~ 配置文件中.
#+begin_src xml
  <?xml version="1.0" encoding="UTF-8"?>
  <beans xmlns="http://www.springframework.org/schema/beans"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:context="http://www.springframework.org/schema/context"
         xsi:schemaLocation="http://www.springframework.org/schema/beans
      http://www.springframework.org/schema/beans/spring-beans.xsd
      http://www.springframework.org/schema/context
      http://www.springframework.org/schema/context/spring-context.xsd">

      <import resource="classpath:spring-dao.xml"/>
      <import resource="spring-service.xml"/>
      <import resource="springmvc-servlet.xml"/> <!--这个配置文件是在后
      面添加的-->
  </beans>
#+end_src

然后在 ~src/test/java/com/kunpeng/dao/~ 目录下创建 ~BookMapperTest.java~
在测试目录中最好对应测试的类和测试的方法. 项目越大,这种方式会非常好用.
#+begin_src java
  //注入BooksService 
  @Autowired
  // service 层中注册的bean
  @Qualifier("booksServiceImpl")
  private BooksService booksService;
  @Test
  public void queryAllTest(){
      ApplicationContext context = new ClassPathXmlApplicationContext("applicationContext.xml");
      BooksService bean = (BooksService) context.getBean("booksServiceImpl");
      List<Books> books = bean.queryAllBook();
      for (Books book : books) {
          System.out.println(book);
      }
  }
#+end_src
*确保上面的代码运行成功,在继续下面的内容!*

*** 配置web
这里怎么配置web查看 ~SpringMVC~ 中的环境配置.

配置成功后确保生成了 ~web/WEB-INF/web.xml~ 配置文件,web路径和src同级.

这里的 ~web.xml~ 的配置和之前一样.
#+begin_src xml
  <?xml version="1.0" encoding="UTF-8"?>
  <web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd"
           version="4.0">
  <!--    DispatcherServlet-->
      <servlet>
          <servlet-name>springmvc</servlet-name>
          <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
          <init-param>
              <param-name>contextConfigLocation</param-name>
              <param-value>classpath:applicationContext.xml</param-value>
          </init-param>
          <load-on-startup>1</load-on-startup>
      </servlet>

      <servlet-mapping>
          <servlet-name>springmvc</servlet-name>
          <url-pattern>/</url-pattern>
      </servlet-mapping>

  <!--    过滤器,解决乱码问题-->
      <filter>
          <filter-name>encodingFilter</filter-name>
          <filter-class>org.springframework.web.filter.CharacterEncodingFilter</filter-class>
          <init-param>
              <param-name>encoding</param-name>
              <param-value>utf-8</param-value>
          </init-param>
      </filter>

      <filter-mapping>
          <filter-name>encodingFilter</filter-name>
          <url-pattern>/*</url-pattern>
      </filter-mapping>

  <!--    设置过期时间-->
      <session-config>
          <session-timeout>15</session-timeout>
      </session-config>
  </web-app>
#+end_src
 *注意: 这里唯一不同的地方是引用的外部* ~springmvc-servlet.xml~  *配置文
 件,这个配置文件已经注册在* ~applicationContext.xml~ 文件中, 所以这里
 只需要 ~applicationContext.xml~ 配置文件. 而不是引用
 ~springmvc-servlet.xml~ 配置文件. *这里也是一个坑!!!*

 配置 ~springvmc-servlet.xml~ 文件,这里的配置文件和 ~SpringMVC~ 环境中
 的一样.
 #+begin_src xml
   <?xml version="1.0" encoding="UTF-8"?>
   <beans xmlns="http://www.springframework.org/schema/beans"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:p="http://www.springframework.org/schema/p"
          xmlns:context="http://www.springframework.org/schema/context"
          xmlns:mvc="http://www.springframework.org/schema/mvc"
          xsi:schemaLocation="
           http://www.springframework.org/schema/beans
           http://www.springframework.org/schema/beans/spring-beans.xsd
           http://www.springframework.org/schema/context
           http://www.springframework.org/schema/context/spring-context.xsd
           http://www.springframework.org/schema/mvc
           http://www.springframework.org/schema/mvc/spring-mvc.xsd">
   <!--扫描包-->
       <context:component-scan base-package="com.kunpeng.controller"/>
   <!--    静态资源过滤-->
       <mvc:default-servlet-handler/>
   <!--注解驱动-->
       <mvc:annotation-driven>
           <mvc:message-converters register-defaults="true">
               <bean class="org.springframework.http.converter.StringHttpMessageConverter">
                   <property name="supportedMediaTypes">
                       <list>
                           <value>text/html;charset=UTF-8</value>
                           <value>application/json;charset=UTF-8</value>
                           <value>text/plain;charset=UTF-8</value>
                           <value>application/xml;charset=UTF-8</value>
                       </list>
                   </property>
               </bean>
           </mvc:message-converters>
       </mvc:annotation-driven>
       <!-- ... -->

       <bean id="viewResolver" class="org.springframework.web.servlet.view.InternalResourceViewResolver">
           <property name="prefix" value="/WEB-INF/jsp/"/>
           <property name="suffix" value=".jsp"/>
       </bean>

   </beans>
 #+end_src
这个配置文件主要做了四件事情.
+ 加载注解驱动
+ 扫描包
+ 过滤静态资源
+ 解析视图
 *编写完成这个配置之后,要记得注册到* ~applicationContext.xml~ *配置文
  件中!!!*

  
 
*** 编写controller层
在 ~controller~ 目录下添加 ~BookController.java~ 文件,并添加下面代进行
测试.
#+begin_src java
  @Controller
  @RequestMapping("/book")
  public class BookController {
      @Autowired
      @Qualifier("booksServiceImpl")
      private BooksService booksService;

      @ResponseBody
      @GetMapping("/all")
      public String queryAll(){
          List<Books> books = booksService.queryAllBook();
          for (Books book : books) {
              System.out.println(book);
          }
          return JsonUtils.getJson(books);
      }
  }
#+end_src
在 ~queryAll~ 方法中,并没有放回视图,而是直接方法JSON数据,使用了
~@ResponseBody~ 注解.


*** 测试web应用
在启动之前 ~Tomcat~ 之前记得线配置 ~Tomcat~ 并在项目中添加 *lib* 目录,
并将依赖导入.
启动之后访问 http://127.0.0.1:8080/book/all, 如果程序没有任何问题,浏览
器中将显示所有书籍,并以JSON的格式显示.
#+begin_src text
      [{"bookId":1,"bookName":"Java","bookCount":0,"detail":"从入门到放弃"},
      {"bookId":2,"bookName":"Mysql","bookCount":0,"detail":"从删库到跑路"},
      {"bookId":3,"bookName":"Linux","bookCount":0,"detail":"从进门到牢底坐穿"}]
#+end_src


后续只需要在 ~dao~ ~service~ ~controller~ 层中添加业务代码即可,其他配
置一次就行了.
*** 总结
这里只是完成ssm整合的环境,只写了几个测试业务,在这个过程中,配置文件就有
七八个,这是一个非常繁琐配置过程,大部分配置只需要配置一次,后续都不需要
改动. 大量的配置文件导致第一次学ssm整合的时候不太友好,先不说能不能看懂
这些配置文件,能把这个环境搭建起来就已经不容易了,在搭建的时候还会遇到各
种各样的问题,不过凡是都有第一次,完成一次搭建,并解决搭建环境的过程中遇
到的问题,才能有所提升,后面再次搭建同样的环境也就不会一头雾水了.

学习是件很奇妙的事情,当我们学习一些知识很轻松的时候,其实是学部到什么东
西的,因为你已经理解了这种思维方式,只有当我们学习起来非常吃力的时候,才
是我们收获最大的时候.

