#+TITLE: Vue 笔记

* 基础
** Vue.js是什么
Vue是一套用于构建用户界面的 *渐进式框架* 。 与其他大型框架不同的是，Vue被设计为可以自底向上逐层应用。Vue的核心库只关注视图层，不仅易于上手，害便于第三方库或既有项目整合。另一方面，当与现代工具链以及各种支持类库使用时，Vue也完全能够为复杂的单页应用提供驱动。

** 按照
Vue基本不用按照任何应用程序在本地，就可以使用Vue.js,最简单的使用方式是创建一个 *.html* 文件，然后通过下面方式引用Vue：
#+begin_src html
  <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
#+end_src

** 声明式渲染
Vue.js的核心是一个允许采用简洁的模板语法来声明式的将数据渲染进DOM的系统：
#+begin_src html
  <div id ="app">
    {{ message }}
  </div>

  <script>
    var app = new Vue({
    el: '#app',
    data: {message:'hello Vue!'}
    })
  </script>
#+end_src

在html中添加上面代码，代码看起来很简单，但是Vue在背后做了大量工作。现在数据和DOM已经被建立了关联，所有东西都是 *响应式的* 。我们通过浏览器的控制台，修改 _app.message_ 的值，网页上的内容也相应的更新。


+ 我们不再和HTML直接交互了。一个Vue应用会将其挂在到一个DOM元素上（上个例子中使用 #app）然后对其进行完全控制。那个HTML是我们的入口，但其余都会发生在新创建的Vue实例内部。

除了文本插值，还可以像这样来绑定元素attrbute：
#+begin_src html
  <div id="app-2">
    <span v-bind:title="message">
      鼠标悬停几秒钟查看此处动态绑定的提示信息！
    </span>
  </div>
#+end_src

#+begin_src js
  var app2 = new Vue({
    el: '#app-2',
    data: {
      message: '页面加载于 ' + new Date().toLocaleString()
    }
  })
#+end_src

_v-bind_ attribute被称为 *指令* 。指令带有前缀 _v-_, 以表示他们是Vue提供的特殊attribute。在这里，该指令的意思是： 将这个约束节点的 _title_ attribute和Vue实例的 _message_ property保持一致。

再次打开浏览器，在控制台中输入 *app2-message 'new message'* ,就能看见<span>标签的title属性已经更新了。

** 条件与循环
   SCHEDULED: <2021-10-25 一>
控制切换元素也非常的简单：
#+begin_src html
  <div id="app-3">
    <p v-if="seen">现在你看到我了</p>
  </div>
#+end_src

#+begin_src js
  var app3 = new Vue({
    el: '#app-3',
    da

ta: {
      seen: true
    }
  })
#+end_src

在控制台中输入 _app3.seen = false_ ,就能看见显示的消息消失了。

这个例子演示了我们不仅可以吧数据绑定到DOM本文或属性中，还是可绑定到DOM结构。

_v-for_ 指令可以绑定数组的数据来渲染一个项目列表：

** 模板语法
   Vue.js使用了基于HTML的模板语法，允许开发者声明式的将DOM绑定至底层Vue实例的数据。所有Vue.js的模板都是合法的HTML
** 计算属性和侦听器
*** 计算属性
    计算属性在调用方法时，主要有两点区别：
    + 表达式上的区别，一般调用方法时后面都会加 *括号* ，而计算属性在调用方法时 *不需要加括号* 。
    + 在内容更新上的区别，一般情况下调用方 *法都会执行方法中的语句* ，不同的是 *计算属性是基于它们的响应依赖关系缓存的* 。计算属性只在相关响应式依赖发生改变时才会重新求值。

    计算属性默认只有getter,在需要时也可以显示的提供一个setter.

*** 侦听器
    Vue是通过 ~watch~ 选项提供一个更通用的方法，来响应数据的变化。当需要在数据变化时执行异步或开销较大的操作时，这个方式是最有用的。

    参考[[https://v3.cn.vuejs.org/guide/computed.html#%E8%AE%A1%E7%AE%97%E5%B1%9E%E6%80%A7%E7%9A%84-setter][官网]]的例子

    watch会监听我们需要监听的内容，只有达到要求才会执行方法，没有达到要求是不会执行方法的。

    *大多数情况下我们使用计算属性就可以了*

* 使用npm构建vue项目
** 安装nodejs
   [[https://nodejs.org/zh-cn/][nodejs官网]]下载长期维护版本，在windows中直接next就能完成安装，并且包括npm。
   在archlinux中安装需要安装以下包：
   #+begin_src shell
     sudo pacman -S nodejs npm # 安装这两个包，这两个包是独立的
   #+end_src
   因为archlinux是滚动发行版，所以安装的一般都是最新的，如果需要安装稳定的可以使用以下命令搜索稳定的版本
   #+begin_src shell
     sudo pacman -S nodejs-lts
   #+end_src
   再根据自己的需要安装即可

   *如果需要使用国内加速可自行百度，我这里使用的是代理，所以默认即可。*

   *最后验证安装是否生效*
   #+begin_src shell
     node -v

     npm -v
   #+end_src
   输出自己安装的版本代表安装成功。

** 安装vue
   命令
   #+begin_src shell
     sudo npm install -g @vue/cli
   #+end_src
   -g 代表全局安装，全局安装就需要使用sudo管理员权限，windows中需要使用管理员权限打开cmd

   安装完成之后使用以下命令验证安装：
   #+begin_src shell
     vue -V
   #+end_src

   有版本信息输出代表安装成功。

** 创建第一个项目
   使用以下命令：
   #+begin_src shell
     vue init webpack myvue # 如果提示没有vue-init,安装提示内容安装即可，按照提示信息一步一步创建即可
     cd myvue
     npm install #安装依赖，前面可能已经执行过了
     npm run dev #运行
   #+end_src

   确保上面命令运行成功，就可以访问 ~http://localhost:8080~ url地址，看到Vue的图标表示一个基本的项目创建成功。
   

   
